// install.js - Project Auto-Installer Script
// This script is generated by Manus AI to set up the entire project environment.

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

// Define all files to be created
const files = {
  'package.json': `{
    "name": "my-project",
    "version": "1.0.0",
    "private": true,
    "scripts": {
      "dev": "next dev",
      "build": "next build",
      "start": "next start",
      "lint": "next lint"
    },
    "dependencies": {
      // ... dynamically injected by AI based on tech stack
    }
  }`,
  
  // Example frontend file
  'app/page.tsx': `'use client';
export default function Home() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-between p-24">
      <h1>Welcome to the Project</h1>
    </main>
  );
}`,

  // ... other dynamically generated files
};

console.log('🚀 Starting project generation...');

// Create directories and write files
for (const [filePath, content] of Object.entries(files)) {
  const fullPath = path.join(process.cwd(), filePath);
  const dir = path.dirname(fullPath);
  
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
  
  fs.writeFileSync(fullPath, content);
  console.log(\`✅ Created file: \${filePath}\`);
}

console.log('📦 Installing dependencies... (this may take a minute)');
try {
  execSync('npm install', { stdio: 'inherit' });
  console.log('✅ Dependencies installed successfully.');
} catch (error) {
  console.error('❌ Failed to install dependencies. You may need to run "npm install" manually.');
}

console.log('🎉 Project setup complete!');
console.log('\\n📝 Next steps:');
console.log('1. Review and update environment variables (e.g., .env.local)');
console.log('2. Run "npm run dev" to start the development server');
console.log('3. Commit and push to GitHub for Zeabur deployment');
